# Generated by Django 5.0.7 on 2025-07-22 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('date', models.DateField()),
                ('recipient_name', models.CharField(default='FixSmart', max_length=100)),
                ('recipient_position', models.CharField(default='Co-ordinator', max_length=100)),
                ('recipient_department', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('pincode', models.CharField(max_length=10)),
                ('landmark', models.CharField(blank=True, max_length=100)),
                ('area', models.CharField(blank=True, max_length=100)),
                ('village', models.CharField(blank=True, max_length=100)),
                ('mandal', models.CharField(blank=True, max_length=100)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('message', models.TextField()),
                ('signature', models.CharField(max_length=150)),
                ('captured_image', models.ImageField(blank=True, null=True, upload_to='complaint_images/')),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('solved_image', models.ImageField(blank=True, null=True, upload_to='solved_images/')),
                ('solved_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SmartFix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('mname', models.CharField(blank=True, max_length=50, null=True)),
                ('lname', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('landmark', models.CharField(blank=True, max_length=100, null=True)),
                ('village', models.CharField(max_length=100)),
                ('mandal', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('district', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('type', models.CharField(default='User', max_length=200)),
                ('designated_at', models.CharField(default=None, max_length=200)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('position', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
