# Generated by Django 5.0.7 on 2025-07-22 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixsmarta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartfix',
            name='designated_at',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
