# Generated by Django 5.0.7 on 2025-07-23 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixsmarta', '0002_alter_smartfix_designated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='mobile',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
    ]
