# Generated by Django 5.0.7 on 2025-07-23 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixsmarta', '0003_complaint_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartfix',
            name='type',
            field=models.CharField(blank=True, default='User', max_length=200, null=True),
        ),
    ]
