# Generated by Django 5.0.7 on 2025-07-23 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixsmarta', '0004_alter_smartfix_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smartfix',
            name='type',
        ),
        migrations.AlterField(
            model_name='smartfix',
            name='position',
            field=models.CharField(blank=True, default='User', max_length=100, null=True),
        ),
    ]
