# Generated by Django 5.0.7 on 2025-07-24 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fixsmarta', '0006_complaint_assigned_to'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='date',
            new_name='complaint_date',
        ),
    ]
