# Generated by Django 5.0.7 on 2025-07-24 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixsmarta', '0007_rename_date_complaint_complaint_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='complaint_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
