# Generated by Django 5.0.7 on 2025-07-24 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixsmarta', '0008_alter_complaint_complaint_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='captured_image',
            field=models.ImageField(blank=True, default=0, upload_to='complaint_images/'),
            preserve_default=False,
        ),
    ]
