# Generated by Django 5.0.7 on 2025-07-24 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixsmarta', '0009_alter_complaint_captured_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='suggestion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
